urls.py

from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("",views.index ,name="index"),
    path("blog/old__url",views.old_url,name="old_url_page"),
    
    path("post/detail/<str:post_id>",views.detail,name="post_details"),
    
    path("contact",views.contact_view,name='contact'),
    
    path("new__url",views.new_url,name = "new_page_url"),
    
    path("about",views.about_view,name="about")
    
    
]

models.py
from typing import Iterable
from django.db import models

from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        
        return self.name


class Post(models.Model):
    
    title = models.CharField(max_length=10000)
    
    content = models.TextField()
    
    img_url = models.URLField(null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    
   
    
    def __str__(self) -> str:
        return self.title
    
class AboutUs(models.Model):
    
    content = models.TextField()
    


forms.py
from django import forms

class ContactForm(forms.Form):
    
    name = forms.CharField(label="Name",max_length=100,required=True)
    
    email = forms.EmailField(label="Email", required=True)
    
    message = forms.CharField(label="Message" ,required=True)

views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Post,AboutUs
import logging
from django.core.paginator import Paginator
from django.http import Http404

from.forms import ContactForm


#posts=[
#        { "id":"1","title":"post","content":"content of post 1 "},
 #       { "id":"2","title":"post","content":"content of post 2"},
  #      { "id":"3","title":"post","content":"content of post 3"},
   #     { "id":"4","title":"post","content":"content of post 4"}
    #]
    # Create your views here.


def index(request):
    
    blog_title = "hello posts"
    
    all_posts=Post.objects.all()
    
    paginator = Paginator(all_posts,5)
    
    page_number=request.GET.get('page')
    
    page_obj=paginator.get_page(page_number)
    
   
    return render(request,"index.html",{"page_obj":page_obj})


def detail(request,post_id):
    
    
    
    
    #post = next((item for item in posts if item["id"] == post_id),None)
    try:
        post=Post.objects.get(pk=post_id)
        
        related_posts = Post.objects.filter(category = post.category).exclude(pk=post.id)
        
    except Post.DoesNotExist:
        
        raise Http404("post doesn not exits")
    
    return render(request,"detail.html",{"post":post,'related_posts':related_posts})



    
    

def old_url(request):
    
    return redirect(reverse('blog:new_page_url'))

def new_url(request):
    
    return HttpResponse("this is new page url")


def contact_view(request):
    
    if request.method == 'POST':
        
        form = ContactForm(request.POST)
        
        
    
    return render(request,"contact.html")
def about_view(request):
    
    about_content=AboutUs.objects.first().content
    
    
    
    return render(request,"about.html",{'about_content':about_content})
    
    


    
    
    
    

templates/about.html
{% extends "base.html" %}

{%block content%}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
               {{about_content}}
            </div>
            
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "blog/style.css" %}">
</head>
<body >
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h3>Blog </h3>
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="/">Home</a>
                    <a class="text-light text-decoration-none" href="/about">About</a>
                    <a class="text-light text-decoration-none" href="/contact">Contact</a>
                </div>
            </div>
        </div>
    </header>
    
    {% block content %}
    {% endblock  %}

    <footer class="bg-dark text-light p-3 fixed-bottom">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/contact.html
{% extends "base.html" %}


{%block content%}
<div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>
                <form method="post" class="row g-3">

                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
</div>


{% endblock %}

templates/detail.html
{% extends "base.html" %}

{%block content%}

    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small>({{post.category.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at}} </p>
              <img src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                  {%for related_post in related_posts%} 
                    <li><a href="{% url "blog:post_details" post_id=related_post.id %}">{{related_post.title}}</a></li>
                  {%endfor%}
                   
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>

{% endblock %}


    

templates/index.html
 {% extends "base.html" %}


{%block content%}


   
    <div class="container-fluid ">
        <div class="row">
            <h2 >Latest Posts</h2>
        </div>
       
        <div class="row m-3 " >
            {% for post in page_obj%}
            <div class="col-4 mb-2 " >
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img  style = "height:300,width:300"src="{{post.img_url}}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8 " >
                                <h5 class="card-title"> {{post.title}}</h5>
                                <p class="card-text">{{post.content|truncatechars:50}}{{post.id}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url "blog:post_details" post_id=post.id %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col-12 my-3">

                {% if page_obj.has_other_pages %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {%if page_obj.has_previous%}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo; first</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">previous</span>
                                </a>
                            </li>
                            {%endif%}
                            <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                            {%if page_obj.has_next%}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">next</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                    <span aria-hidden="true">last &raquo;</span>
                                </a>
                            </li>
                            {%endif%}
                        </ul>
                    </nav>
                {%endif%}
                
            </div>
            
        
    </div>

{% endblock %}
   